---
title: "tutorial1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

In week 1, we learned some important results for set operations such as De Morgan's Law. Another useful results is the **distributive law**, which states the following: $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$ and $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$.
(a) Draw Venn diagrams to illustrate these results.
(b) Suppose $\Omega = \{1, 2, 3, 4, 5, 6\}$ and let $A = \{1, 2, 4, 5\}, B = \{1, 3, 5\}$ and $C = \{2, 4, 6\}$. Use this example to verify the two results in the distributive law.

## Question 2

In R, write R code to simulate rolling a fair six-sided die once, 10 times, 100 times, and 1000 times.
(a) Estimate the probability of rolling a 3 or higher based on 1000 simulated dice rolls.
(b) If you were to repeat your simulation, would you end up with the same estimate? Why or why not.

## Question 3

Consider the word "STATISTICS". Is the number of _unique_ arrangements of the letters in "STATISTICS" 10! ? Justify your answer and compute the probability that a random rearrangement of the letters in "STATISTICS" will spell the word "STATISTICS".

## Question 4

Assume birthdays are equally likely to occur in each of the 12 months of the year. What is the probability that at least two people in a group of three students have birth months in common? Be sure to show your steps.
